import Head from 'next/head'
import styles from '../styles/cart.module.css'
import Header from '@/components/header'
import Image from 'next/image'
export default function NFT() {
  return (
    <>
    <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft-1.svg" />
      </Head>
    <main >
      <Header/>
      
      <section className="relative justify-center items-center bg-gradient-to-r from-gray-700 to-gray-950 text-white pt-4 sm:p-16 xs:p-8 px-6 py-12">
      <h1 className="text-teal-300 text-4xl	font-serif	text-center	m-10	">
        NFT
      </h1>
      <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-cyan-300 sm:text-6xl">
              Data to enrich your online business
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-600">
              Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet
              fugiat veniam occaecat fugiat aliqua.
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <a
                href="#"
                className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Get started
              </a>
              <a href="#" className="text-sm font-semibold leading-6 text-cyan-300">
                Learn more <span aria-hidden="true">→</span>
              </a>
            </div>
          </div>
  <div className="flex justify-center items-center 3xl:max-w-[1280px] w-full flex-col"> 
  </div>
  <div className="flex flex-col md:flex-row max-w-5xl mx-auto my-auto justify-center space-y-4 md:space-y-0 md:space-x-4">
    <div className="p-4 max-w-md">
      <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
        <Image
          className="h-48 w-full object-cover object-center"
          src="/eth.png"
          width={100}
          height={48}
          alt="blog"
        />
        <div className="p-6">
          <h1 className="title-font text-lg font-medium text-cyan-200 text-center mb-3">
            Build an AI powered movie application using react
          </h1>
          <p className="leading-relaxed mb-3 text-center">
            Kiss theory-driven courses goodbye and build an interactive movie app that showcases your development prowess
          </p>
          <div className="flex items-center justify-center">
            <button className="text-white rounded-full border px-4 py-2 bg-blue-500 inline-flex items-center cursor-pointer hover:bg-blue-800 transition-all duration-300">
              Learn More
              <svg
                className="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth="2"
                fill="none"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div className="p-4 max-w-md">
      <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
        <Image
          className="h-48 w-full object-cover object-center"
          src="/nft.jpg"
          width={100}
          height={48}
          alt="blog"
        />
        <div className="p-6">
          <h1 className="title-font text-lg font-medium text-cyan-200 text-center mb-3">
            Build an AI powered movie application using react
          </h1>
          <p className="leading-relaxed mb-3 text-center">
            Kiss theory-driven courses goodbye and build an interactive movie app that showcases your development prowess
          </p>
          <div className="flex items-center justify-center">
            <button className="text-white rounded-full border px-4 py-2 bg-blue-500 inline-flex items-center cursor-pointer hover:bg-blue-800 transition-all duration-300">
              Learn More
              <svg
                className="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth="2"
                fill="none"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
   
  </div>
</section>
    </main>
    </>
  )
}
