import Head from 'next/head'
import styles from '../styles/login.module.css'
import Image from 'next/image'
export default function Singup() {
    return (
      <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft-1.svg" />
      </Head>
      <main>
      <div>
    <Image
      layout="fill"
      className="absolute"
      objectFit="cover"
      src="/bgim.jpg"
      alt="background"
    />    
    
      <div className="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8 relative ">
        <div className="sm:mx-auto sm:w-full sm:max-w-sm">
        <Image
      src="/ethereum.png"
      width={50}
      height={50}
      className="mx-auto h-10 w-auto" 
      alt="Picture of the author"
    />
         
          <h2 className="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-cyan-300	">
            Sign up to your account
          </h2>
        </div>
       
  

        <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm ">
          <form className="space-y-6" action="#" method="POST">
            <div>
              <label htmlFor="name" className="block text-sm font-medium leading-6 text-cyan-300	">
                Full Name
              </label>
              <div className="mt-2">
                <input
                  id="name"
                  name="name"
                  type="text"
                  autoComplete="name"
                  required
                  className="block w-full rounded-md  border-dotted border-2 border-cyan-300 border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>
            <div>
              <label htmlFor="text" className="block text-sm font-medium leading-6 text-cyan-300	">
                Phone Number
              </label>
              <div className="mt-2">
                <input
                  id="name"
                  name="number"
                  type="number"
                  autoComplete="name"
                  required
                  className="block w-full rounded-md border-dotted border-2 border-cyan-300 border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>
            <div>
              <label htmlFor="email" className="block text-sm font-medium leading-6 text-cyan-300	">
                Email address
              </label>
              <div className="mt-2">
                <input
                  id="email"
                  name="email"
                  type="email"
                  autoComplete="email"
                  required
                  className="block w-full rounded-md border-0 py-1.5 border-dotted border-2 border-cyan-300 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>

            <div>
              <div className="flex items-center justify-between">
                <label htmlFor="password" className="block text-sm font-medium leading-6 text-cyan-300	">
                  Password
                </label>
                <div className="text-sm">
                  <a href="#" className="font-semibold text-cyan-300	 hover:text-indigo-500">
                    Forgot password?
                  </a>
                </div>
              </div>
              <div className="mt-2">
                <input
                  id="password"
                  name="password"
                  type="password"
                  autoComplete="current-password"
                  required
                  className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 border-dotted border-2 border-cyan-300"
                />
              </div>
            </div>

            <div>
              <button
                type="submit"
                className="flex w-full justify-center  bg-cyan-300   rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-black   shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 border-double border-4 border-cyan-300"
              >
                Sign up
              </button>
            </div>
          </form>

          
        </div>
      </div>
      </div>
      
      </main>
      </>
    )
  }
  